name: Automated Backup

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight
  workflow_dispatch:      # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    # Fetch all history
    
    - name: Create dated backup
      run: |
        BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
        tar -czf frontend_backup_${BACKUP_DATE}.tar.gz \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='build' \
          .
    
    - name: Upload backup to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-backup-${{ github.sha }}
        path: frontend_backup_*.tar.gz
        retention-days: 30