name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || echo "No linting configured"
    
    - name: Run tests
      run: npm test -- --passWithNoTests
    
    - name: Build project
      run: npm run build

    - name: Create backup
      run: |
        tar -czf frontend_backup_$(date +%Y%m%d).tar.gz \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='build' \
          .
    
    - name: Upload backup artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-backup-${{ github.sha }}
        path: frontend_backup_*.tar.gz
        retention-days: 14